name: Compile README
on:
  push:
    branches:
      - main
    paths:
      - 'README.gh.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: uukelele/gh-md@main
